# Exploring ACLED dataset

In [2]:
import pandas as pd
df = pd.read_csv("acled_20211224.csv")

In [6]:
print(len(df.columns))
print(df.size)
df.iloc[:, 1:10].head()

31
38207314

,iso,event_id_cnty,event_id_no_cnty,event_date,year,time_precision,event_type,sub_event_type,actor1
0,710,SAF15902,15902.0,26 November 2021,2021,2,Violence against civilians,Sexual violence,Police Forces of South Africa (1994-)
1,364,IRN11785,11785.0,26 November 2021,2021,1,Protests,Peaceful protest,Protesters (Iran)
2,364,IRN11796,11796.0,26 November 2021,2021,1,Protests,Peaceful protest,Protesters (Iran)
3,364,IRN11798,11798.0,26 November 2021,2021,1,Riots,Violent demonstration,Rioters (Iran)
4,275,PSE12790,12790.0,26 November 2021,2021,1,Riots,Mob violence,Rioters (Palestine)

In [7]:
df.iloc[:, 10:20].head()

,assoc_actor_1,inter1,actor2,assoc_actor_2,inter2,interaction,region,country,admin1,admin2
0,NaN,1,Civilians (South Africa),Women (South Africa); Prisoners (South Africa),7,17,Southern Africa,South Africa,KwaZulu-Natal,iLembe
1,Women (Iran),6,NaN,NaN,0,60,Middle East,Iran,Kurdistan,Sannandaj
2,NaN,6,NaN,NaN,0,60,Middle East,Iran,Lorestan,Khorramabad
3,Farmers (Iran),5,Police Forces of Iran (1989-),NaN,1,15,Middle East,Iran,Isfahan,Isfahan
4,Refugees/IDPs (Palestine),5,Military Forces of Israel (2021-),NaN,8,58,Middle East,Palestine,West Bank,Bethlehem

In [8]:
df.iloc[:, 20:].head()

,admin3,location,latitude,longitude,geo_precision,source,source_scale,notes,fatalities,timestamp,iso3
0,Maphumulo,Maphumulo,-29.1500,31.0666,1,News24 (South Africa),National,"Around 26 November 2021 (as reported), a case ...",0,1638462528,ZAF
1,Central,Sanandaj,35.3150,46.9988,1,Free Union of Iranian Workers; Kurdistan Human...,Other,"On 26 November 2021, women rallied in the Abid...",0,1638196779,IRN
2,Central,Khorramabad,33.4878,48.3558,1,Eteraze Bazar; Iran Kargar,New media,"On 26 November 2021, residents protested near ...",0,1638196779,IRN
3,Central,Isfahan,32.6525,51.6746,1,Iran International; Radio Farda; Iran Kargar; ...,Other-New media,"On 26 November 2021, farmers and supporters co...",0,1638196779,IRN
4,NaN,Mukhayyam Ayidah,31.7195,35.1986,1,Palestine News and Information Agency; Dunia A...,National,"On 26 November 2021, Palestinian rioters clash...",0,1638196779,PSE

In [10]:
len(df["country"].unique())

207

In [11]:
len(df["region"].unique())

15

In [12]:
df["region"].unique()

array(['Southern Africa', 'Middle East', 'South America',
       'Central America', 'North America', 'Caribbean', 'Western Africa',
       'Eastern Africa', 'Northern Africa', 'Middle Africa', 'East Asia',
       'Southeast Asia', 'South Asia', 'Europe',
       'Caucasus and Central Asia'], dtype=object)

In [21]:
aux = df[df['region'].str.contains("Asia|Middle East")]
aux["region"].unique()

array(['Middle East', 'East Asia', 'Southeast Asia', 'South Asia',
       'Caucasus and Central Asia'], dtype=object)

In [22]:
len(aux["country"].unique())

48

In [28]:
aux.to_csv("acled_asia_2021.csv", index=False)

In [29]:
dg = pd.read_csv("acled_asia_2021.csv")

In [30]:
dg.head()

,data_id,iso,event_id_cnty,event_id_no_cnty,event_date,year,time_precision,event_type,sub_event_type,actor1,...,location,latitude,longitude,geo_precision,source,source_scale,notes,fatalities,timestamp,iso3
0,8658794,364,IRN11785,11785.0,26 November 2021,2021,1,Protests,Peaceful protest,Protesters (Iran),...,Sanandaj,35.3150,46.9988,1,Free Union of Iranian Workers; Kurdistan Human...,Other,"On 26 November 2021, women rallied in the Abid...",0,1638196779,IRN
1,8658804,364,IRN11796,11796.0,26 November 2021,2021,1,Protests,Peaceful protest,Protesters (Iran),...,Khorramabad,33.4878,48.3558,1,Eteraze Bazar; Iran Kargar,New media,"On 26 November 2021, residents protested near ...",0,1638196779,IRN
2,8658806,364,IRN11798,11798.0,26 November 2021,2021,1,Riots,Violent demonstration,Rioters (Iran),...,Isfahan,32.6525,51.6746,1,Iran International; Radio Farda; Iran Kargar; ...,Other-New media,"On 26 November 2021, farmers and supporters co...",0,1638196779,IRN
3,8658881,275,PSE12790,12790.0,26 November 2021,2021,1,Riots,Mob violence,Rioters (Palestine),...,Mukhayyam Ayidah,31.7195,35.1986,1,Palestine News and Information Agency; Dunia A...,National,"On 26 November 2021, Palestinian rioters clash...",0,1638196779,PSE
4,8658900,275,PSE12826,12826.0,26 November 2021,2021,1,Riots,Violent demonstration,Rioters (Palestine),...,Bayta,32.1414,35.2855,1,Palestine News and Information Agency; Dunia A...,National-Regional,"On 26 November 2021, Palestinian rioters clash...",0,1638196779,PSE

In [34]:
aux2 = dg[["data_id", "event_date", "iso3", "event_type", "fatalities"]]
aux2.to_csv("acled_asia_2021_subset.csv", index=False)